name: laptop price prediction

on:
  push:
    branches: [ "main" ]  # Trigger workflow only on pushes to main branch

jobs:
  ci-and-deploy-to-qatest:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Keeps workflow credentials so it can push changes safely.
          # This prevents anyone from pushing directly to the branch without going through the workflow.
          persist-credentials: true  
          token: ${{ secrets.GITHUB_TOKEN }}
      # Step 2: Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install all packages listed in requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: pytest  # Run all tests, workflow stops here if tests fail

      # Step 5: Push to qatest branch if tests pass
      - name: Push changes to qatest branch
        run: |
          # Set git identity for the workflow commits
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"


          # Create or switch to 'qatest' branch
          git checkout -B qatest  

          # Push changes to 'qatest' branch; --force overwrites if it already exists
          git push origin qatest --force
