name: Laptop Price Prediction CI

on:
  push:
    branches: [ "main" ]  # Trigger workflow only on push to main

jobs:
  ci-and-deploy-to-qatest:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Keeps workflow credentials so it can push changes safely.
          # This prevents anyone from pushing directly to the branch without going through the workflow.
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: pytest

      # Step 5: Push changes to qatest branch (only runs if tests pass)
      - name: Push changes to qatest branch
        if: success()  # This ensures the step runs only if previous steps succeed
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Set git identity for workflow commits
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Create or switch to qatest branch
          git checkout -B qatest

          # Push using token authentication to avoid 403
          git push https://x-access-token:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git qatest --force

          #qatest --force and checkout -b only the qatest brach we can access

          # and more over the github token genrate had some steps like 
          #-> repo settings -> workflow permissions -> enable read and write permissions ->chosse allow github approval to pull_request
           
